name: Build APK from ZIP
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Unzip and Build
        run: |
          LATEST_ZIP=$(ls -t *.zip | head -n 1)
          unzip -q "$LATEST_ZIP" -d project
          
          # الدخول لمجلد المشروع اللي فيه ملف build.gradle
          GRADLE_DIR=$(find project -name "build.gradle" -exec dirname {} \; | head -n 1)
          cd "$GRADLE_DIR"
          
          # البناء باستخدام جرادل السيرفر الجاهز مباشرة بدون gradlew المكسور
          gradle assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: '**/build/outputs/apk/debug/app-debug.apk'
