name: Build APK from ZIP
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Unzip
        run: |
          # فك ضغط المشروع
          unzip -q "*.zip" -d project
          # الدخول للمجلد وفك الضغط أو التعامل مع الملفات مباشرة
          cd project
          # إعطاء صلاحية التنفيذ للجرادل
          chmod +x gradlew
          # بناء التطبيق
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug
          path: '**/build/outputs/apk/debug/app-debug.apk'

